backend:
  name: git-gateway
  branch: main
media_folder: "_site/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "components"
    label: "components"
    files:
      - name: "info"
        label: "Info"
        file: "src/_data/info.json"
        fields:
          - { label: "name", name: "name", widget: string }
          - { label: "email", name: "email", widget: string }
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navbar.json"
        fields:
          - { label: "brand", name: "brand", widget: string }
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
      - name: "footer"
        label: "footer"
        file: "src/_data/footer.json"
        fields:
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - { name: "subheading", label: "subheading", widget: "string" }
          - { name: "copyright", label: "copyright", widget: "string" }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
          - name: "recht"
            label: "recht"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
          - name: "socials"
            label: "socials"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
      - name: "hero"
        label: "hero"
        file: "src/_data/hero.json"
        fields:
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Hero Subheading", name: "hero_sub", widget: "string" }
          - { label: "Hero Button", name: "hero_btn", widget: "string" }
      - name: "cta"
        label: "cta"
        file: "src/_data/cta.json"
        fields:
          - { label: "Cta Heading", name: "cta_heading", widget: "string" }
          - { label: "Cta Subheading", name: "cta_sub", widget: "string" }
          - { label: "Cta Button", name: "cta_button", widget: "string" }
      - name: "benefits"
        label: "benefits"
        file: "src/_data/benefits.json"
        fields:
          - { label: "dummy", name: "dummy", widget: hidden }
          - name: "benefit"
            label: "benefit"
            widget: "list"
            fields:
              - { name: "icon", label: "icon", widget: "string" }
              - {
                  name: "benefit_title",
                  label: "Benefit Title",
                  widget: "string",
                }
              - {
                  name: "benefit_text",
                  label: "Benefit Text",
                  widget: "string",
                }
      - name: "process"
        label: "process"
        file: "src/_data/process.json"
        fields:
          - { label: "title", name: "title", widget: string }
          - { label: "desc", name: "desc", widget: string }
          - name: "steps"
            label: "steps"
            widget: "list"
            fields:
              - { name: "image", label: "image", widget: "string" }
              - {
                  name: "benefit_title",
                  label: "Benefit Title",
                  widget: "string",
                }
              - name: "bulletpoints"
                label: "bulletpoints"
                widget: "list"
                fields:
                  - {
                      name: "bulletpoint",
                      label: "bulletpoint",
                      widget: "string",
                    }
      - name: "socials"
        label: "socials"
        file: "src/_data/socials.json"
        fields:
          - { label: "dummy", name: "dummy", widget: hidden }
          - name: "social"
            label: "social"
            widget: "list"
            fields:
              - { name: "social_text", label: "social Text", widget: "string" }
              - { name: "social_name", label: "social name", widget: "string" }
              - { name: "social_job", label: "social job", widget: "string" }
              - { name: "social_img", label: "social image", widget: "string" }
      - name: "intro1"
        label: "intro1"
        file: "src/_data/intro1.json"
        fields:
          - { name: "title", label: "title", widget: "string" }
          - { name: "desc1", label: "desc1", widget: "string" }
          - { name: "desc2", label: "desc2", widget: "string" }
          - { name: "image", label: "image", widget: "string" }
          - name: "bulletpoints"
            label: "bulletpoints"
            widget: "list"
            fields:
              - { name: "bulletpoint", label: "bulletpoint", widget: "string" }
      - name: "intro2"
        label: "intro2"
        file: "src/_data/intro2.json"
        fields:
          - { name: "title", label: "title", widget: "string" }
          - { name: "desc1", label: "desc1", widget: "string" }
          - { name: "image", label: "image", widget: "string" }
          - name: "bulletpoints"
            label: "bulletpoints"
            widget: "list"
            fields:
              - { name: "bulletpoint", label: "bulletpoint", widget: "string" }
  - name: "projekte"
    label: "Projekte"
    folder: "src/projekte"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - {
          label: "featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "displayOrder", name: "displayOrder", widget: "number" }
      - { label: "body", name: "body", widget: "markdown" }

  - name: "blogposts"
    label: "Blogposts"
    folder: "src/blogposts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - { label: "body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/index.html"
        fields:
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/home.html",
            }
          - { label: Title, name: title, widget: string }
          - label: "Page Cta"
            name: "page_cta"
            widget: "object"
            fields:
              - {
                  label: "Cta Heading",
                  name: "cta_heading",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Subheading",
                  name: "cta_sub",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Button",
                  name: "cta_button",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
      - name: "about"
        label: "About"
        file: "src/about.html"
        fields:
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/about.html",
            }
          - { label: Title, name: title, widget: string }
          - { label: heading, name: heading, widget: string }
          - { label: desc, name: desc, widget: string }
          - { label: heading2, name: heading2, widget: string }
          - { label: desc2, name: desc2, widget: string }
          - { label: desc3, name: desc3, widget: string }
          - {
              label: "about_img",
              name: "about_img",
              widget: "image",
              required: true,
            }
          - label: "Page Cta"
            name: "page_cta"
            widget: "object"
            fields:
              - {
                  label: "Cta Heading",
                  name: "cta_heading",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Subheading",
                  name: "cta_sub",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Button",
                  name: "cta_button",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
      - name: "projekte"
        label: "projekte"
        file: "src/projekte.html"
        fields:
          - { label: Title, name: title, widget: string, default: "Projekte" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/projekte.html",
            }
          - label: "header"
            name: "header"
            widget: "object"
            fields:
              - { label: "heading", name: "heading", widget: "string" }
              - { label: "sub", name: "sub", widget: "string" }
          - label: "pagination"
            name: "pagination"
            widget: "object"
            fields:
              - { label: "data", name: "data", widget: "string" }
              - { label: "size", name: "size", widget: "number" }
          - { label: permalink, name: permalink, widget: string }
          - {
              label: paginationPrevText,
              name: paginationPrevText,
              widget: string,
            }
          - {
              label: paginationNextText,
              name: paginationNextText,
              widget: string,
            }
          - { label: paginationAnchor, name: paginationAnchor, widget: string }
          - label: "Page Cta"
            name: "page_cta"
            widget: "object"
            fields:
              - {
                  label: "Cta Heading",
                  name: "cta_heading",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Subheading",
                  name: "cta_sub",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Button",
                  name: "cta_button",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
      - name: "blog"
        label: "blog"
        file: "src/blog.html"
        fields:
          - { label: Title, name: title, widget: string, default: "blog" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/blog.html",
            }
          - label: "header"
            name: "header"
            widget: "object"
            fields:
              - { label: "heading", name: "heading", widget: "string" }
              - { label: "sub", name: "sub", widget: "string" }
          - label: "pagination"
            name: "pagination"
            widget: "object"
            fields:
              - { label: "data", name: "data", widget: "string" }
              - { label: "size", name: "size", widget: "number" }
          - { label: permalink, name: permalink, widget: string }
          - {
              label: paginationPrevText,
              name: paginationPrevText,
              widget: string,
            }
          - {
              label: paginationNextText,
              name: paginationNextText,
              widget: string,
            }
          - { label: paginationAnchor, name: paginationAnchor, widget: string }
          - label: "Page Cta"
            name: "page_cta"
            widget: "object"
            fields:
              - {
                  label: "Cta Heading",
                  name: "cta_heading",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Subheading",
                  name: "cta_sub",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
              - {
                  label: "Cta Button",
                  name: "cta_button",
                  widget: "string",
                  required: false,
                  hint: "Standard CTA wird genommen",
                }
      - name: "kontakt"
        label: "kontakt"
        file: "src/kontakt.html"
        fields:
          - { label: Title, name: title, widget: string, default: "kontakt" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/kontakt.html",
            }
          - { label: heading, name: heading, widget: string }
          - { label: desc, name: desc, widget: string }
          - { label: "contact_img", name: "contact_img", widget: "string" }
      - name: "404"
        label: "404"
        file: "src/404.html"
        fields:
          - { label: Title, name: title, widget: string, default: "kontakt" }
          - {
              label: permalink,
              name: "permalink",
              widget: "string",
              default: "404.html",
            }
          - { label: heading, name: heading, widget: string }
          - { label: desc, name: desc, widget: string }
          - { label: "404_img", name: "404_img", widget: "string" }
